name: cancerenv
channels:
  - pyg
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - cudatoolkit=11.3
  - pytorch>=1.11
  - pytorch-lightning=1.9.4
  - pyg
  - mygene>=3.2
  - numpy>=1.23
  - networkx>=2.8
  - scipy>=1.8
  - tqdm>=4.64
  - pandas>=1.4
  - scikit-learn>=1.1
  - h5py>=3.7
  - wandb>=0.12
  - matplotlib>=3.5
  - seaborn>=0.11
  - jupyter>=1.0
  - setuptools>=59.5
  - pip>=22.1
