name: cancerenv
channels:
  - pyg
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - black>=22.6
  - python>=3.9
  - cudatoolkit=11.6
  - pytorch>=1.11
  - torchvision>=0.12
  - torchaudio>=0.11
  - pytorch-lightning>=1.6
  - pyg>=2.0
  - pysr>=0.9
  - mygene>=3.2
  - numpy>=1.23
  - tensorflow>=2.10
  - networkx>=2.8
  - scipy>=1.8
  - tqdm>=4.64
  - pandas>=1.4
  - scikit-learn>=1.1
  - h5py>=3.7
  - wandb>=0.12
  - matplotlib>=3.5
  - seaborn>=0.11
  - jupyter>=1.0
  - setuptools>=59.5
  - watermark>=2.3
  - pip>=22.1
