name: cancerenv
channels:
  - pyg
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - black
  - python=3.9
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - pysr
  - mygene
  - numpy
  - scipy
  - tqdm
  - pandas
  - scikit-learn
  - h5py
  - wandb
  - optuna
  - matplotlib
  - seaborn
  - jupyter
  - pip
